repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-merge-conflict
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
      - id: detect-secrets
        args: ["--baseline", ".secrets.baseline", "--force-use-all-plugins"]
        exclude: ^(tests/|docs/|.*\.md$)

# To enable:
#   pip install pre-commit detect-secrets
#   pre-commit install
#   detect-secrets scan > .secrets.baseline
