name: Agent Handoff

on:
  issues:
    types: [opened, edited, labeled]

permissions:
  issues: write
  contents: read

jobs:
  handoff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Dispatch agent system prompt
        uses: actions/github-script@v7
        with:
          script: |
            const labels = (context.payload.issue.labels || []).map(l => typeof l === 'string' ? l : l.name);
            const agentLabel = labels.find(n => n && n.startsWith('agent:'));
            if (!agentLabel) {
              core.info('No agent:* label present; skipping');
              return;
            }
            const agentKey = agentLabel.split(':')[1];
            const fs = require('fs');
            const path = `agents/${agentKey}.md`;
            if (!fs.existsSync(path)) {
              core.setFailed(`Agent prompt not found: ${path}`);
              return;
            }
            const body = fs.readFileSync(path, 'utf8');
            const owner = context.repo.owner;
            const repo = context.repo.repo;
            const number = context.issue.number;
            await github.rest.issues.createComment({ owner, repo, issue_number: number, body: `System prompt for ${agentKey} (from ${path}):\n\n` + body });
            core.info(`Posted agent prompt for ${agentKey}`);

