name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  tests-fast:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12", "3.13"]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        shell: bash
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else
            # Minimal deps for tests
            pip install pytest pytest-xdist pytest-forked aiohttp pyyaml numpy
          fi
          # Install observability submodule
          if [ -d external/llm-observability-suite ]; then
            pip install -e external/llm-observability-suite
          fi

      - name: Run fast tests (exclude slow)
        env:
          PYTHONPATH: src
        run: pytest -n auto --dist=loadfile -m "not slow" -q

      - name: Aggregate generation errors (ndjson ledger)
        env:
          PYTHONPATH: src
        run: |
          python scripts/aggregate_generation_errors.py || true

      - name: Upload lb_metrics.ndjson artifact
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: lb-metrics-ndjson
          path: lb_metrics.ndjson
          if-no-files-found: ignore

  lint-format:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install tools
        run: |
          python -m pip install --upgrade pip
          pip install ruff black
      - name: Ruff (lint)
        run: ruff check src tests
      - name: Black (format check)
        run: black --check src tests
