name: E2E Build

on:
  push:
    branches: ["main"]
    tags: ["v*", "release-*" ]
  pull_request:
    branches: ["main"]

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install build tooling
        run: |
          python -m pip install --upgrade pip
          pip install build setuptools wheel

      - name: Lint POML templates (self-contained)
        run: |
          python scripts/lint_poml_self_contained.py

      - name: Build sdist and wheel
        run: |
          python -m build -n
          ls -la dist/

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: story-engine-dist
          path: dist/*

  docker:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ghcr.io/${{ github.repository_owner }}/story-engine:${{ github.sha }}
            ghcr.io/${{ github.repository_owner }}/story-engine:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
