name: Orchestrator Suite

on:
  workflow_dispatch:

jobs:
  orchestrator:
    name: Orchestrator (LMStudio + Kobold)
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-asyncio aiohttp pyyaml
          pip install -e .

      - name: Run orchestrator tests (exclude slow)
        env:
          LOG_FORMAT: json
        run: |
          set -o pipefail
          pytest -q -k "lmstudio or kobold" -m "not slow" --log-cli-level=INFO | tee pytest-orchestrator.log

      - name: Upload orchestrator logs
        uses: actions/upload-artifact@v4
        with:
          name: orchestrator-logs
          path: pytest-orchestrator.log
