name: Tests

on:
  push:
  pull_request:
  workflow_dispatch:
    inputs:
      run_live:
        description: "Run slow/live tests"
        required: false
        default: "false"

jobs:
  unit:
    name: Unit (fast, not slow)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install
        run: |
          python -m pip install --upgrade pip
          pip install -e .
          pip install pytest
      - name: Lint POML templates (self-contained)
        run: |
          python scripts/lint_poml_self_contained.py
      - name: Run tests (exclude slow)
        env:
          PYTHONPATH: src
        run: |
          pytest -q

  repro-harness:
    name: Repro Harness (focused)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install minimal deps
        run: |
          python -m pip install --upgrade pip
          pip install -e .
          pip install pytest
      - name: Run repro harness tests
        env:
          PYTHONPATH: src
        run: |
          pytest -q tests/test_repro_harness.py

  live:
    name: Live (slow, opt-in)
    if: ${{ github.event_name == 'workflow_dispatch' && inputs.run_live == 'true' }}
    runs-on: ubuntu-latest
    env:
      STORY_ENGINE_LIVE: '1'
      LLM_TEST_TIMEOUT: '20'
    steps:
      - name: Join Tailscale (auth key)
        uses: tailscale/github-action@v2
        with:
          authkey: ${{ secrets.TS_AUTHKEY }}
          # If your auth key doesn't embed tags, you can enable the next line
          # but ensure TagOwners in your ACL allow this tag.
          # tags: tag:ci
      - name: Verify Tailscale session
        run: tailscale status
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install
        run: |
          python -m pip install --upgrade pip
          pip install -e .
          pip install pytest
      - name: Point config to ai-lb over Tailscale
        run: |
          sed -i 's#http://localhost:8000#http://pc-sam.dory-phrygian\.ts\.net:8000#' config.yaml
      - name: Quick connectivity check (optional)
        run: |
          curl -sSf http://pc-sam.dory-phrygian.ts.net:8000/v1/models | head -c 200 || true
      - name: Run slow-marked tests
        env:
          PYTHONPATH: src
        run: |
          pytest -q -m slow

  db-live:
    name: Live DB smoke (opt-in)
    if: ${{ github.event_name == 'workflow_dispatch' && inputs.run_live == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install
        run: |
          python -m pip install --upgrade pip
          pip install -e .
          pip install pytest
      - name: Run DB smoke tests
        env:
          DB_WALLET_LOCATION: ${{ secrets.DB_WALLET_LOCATION }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_DSN: ${{ secrets.DB_DSN }}
        run: |
          pytest -q -m db_smoke
