name: tests-fast

on:
  push:
  pull_request:

jobs:
  tests-fast:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12", "3.13"]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install deps
        shell: bash
        env:
          PYTHONPATH: src
        run: |
          python -m pip install --upgrade pip
          # Submodule install
          if [ -d external/llm-observability-suite ]; then pip install -e external/llm-observability-suite; fi
          # Install project for >=3.12; otherwise run from src
          PYOK=$(python - <<'PY'
import sys; print(1 if sys.version_info[:2] >= (3,12) else 0)
PY
)
          if [ "$PYOK" = "1" ]; then
            pip install -e ".[postgres]"
          else
            echo "Skipping package install on Python < 3.12; tests will import from src"
          fi
          pip install pytest pytest-asyncio click

      - name: Run fast tests (exclude slow/oracle/acceptance)
        env:
          PYTHONPATH: src
        run: |
          pytest -n auto --dist=loadfile -m "not slow and not oracle and not acceptance" -q
