name: Tests

on:
  push:
  pull_request:
  workflow_dispatch:
    inputs:
      run_live:
        description: "Run slow/live tests"
        required: false
        default: "false"

jobs:
  unit:
    name: Unit (fast, not slow)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install
        run: |
          python -m pip install --upgrade pip
          pip install -e .
          pip install pytest
      - name: Run tests (exclude slow)
        env:
          PYTHONPATH: src
        run: |
          pytest -q

  live:
    name: Live (slow, opt-in)
    if: ${{ github.event_name == 'workflow_dispatch' && inputs.run_live == 'true' }}
    runs-on: ubuntu-latest
    env:
      STORY_ENGINE_LIVE: '1'
      LLM_TEST_TIMEOUT: '20'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install
        run: |
          python -m pip install --upgrade pip
          pip install -e .
          pip install pytest
      - name: Run slow-marked tests
        env:
          PYTHONPATH: src
        run: |
          pytest -q -m slow
