name: Unit Tests
on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: pip install -U pip
      - run: pip install -e external/llm-observability-suite
      - run: pip install -e ".[postgres]"
      - run: pip install pytest pytest-asyncio
      - name: Run unit tests
        run: pytest -q tests/unit
